// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace PredictiveMaintenanceModel_ConsoleApp1
{
    public partial class PredictiveMaintenanceModel
    {
        /// <summary>
        /// model input class for PredictiveMaintenanceModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"SQUARE_FT")]
            public float SQUARE_FT { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"ADDRESS")]
            public string ADDRESS { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"TARGET(PRICE_IN_LACS)")]
            public float TARGET_PRICE_IN_LACS_ { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PredictiveMaintenanceModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"SQUARE_FT")]
            public float SQUARE_FT { get; set; }

            [ColumnName(@"ADDRESS")]
            public float[] ADDRESS { get; set; }

            [ColumnName(@"TARGET(PRICE_IN_LACS)")]
            public float TARGET_PRICE_IN_LACS_ { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PredictiveMaintenanceModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
